In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
# shuffle module is useful to do random permutations of the collections on arrays.
from sklearn.utils import shuffle
data = pd.read_csv("https://raw.githubusercontent.com/amankharwal/Website-data/master/student-mat.csv")
data.head(5)

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [44]:
# In this dataset the G1 represents the grades of the first period, G2 represents the grades of the second period,
# and G3 represents the final grades.
# I split the dataset into 30% testing and 70% training
data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]]
predict = "G3"
x = np.array(data.drop([predict], 1))
y = np.array(data[predict])

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.3)

/tmp/ipykernel_17775/978717149.py:6: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  x = np.array(data.drop([predict], 1))


In [45]:
lr = LinearRegression()
lr.fit(xtrain, ytrain)
accuracy = lr.score(xtest, ytest)
print(accuracy)

0.7946264794969711


In [46]:
predictions = lr.predict(xtest)
for i in range(len(predictions)):
    print(predictions[x], xtest[x], [ytest[x]])

[[ 7.6173951  12.73903704  7.48717239  8.89516917 12.73903704]
 [ 7.6173951   7.6173951   7.48717239  8.89516917 14.29107938]
 [ 5.99897669 15.22274216  7.48717239  5.4624328  10.27624599]
 ...
 [10.27624599 15.22274216  9.13897189  5.4624328   5.4624328 ]
 [ 7.51273649  9.65950317  9.13897189  8.89516917  8.89516917]
 [15.22274216 11.7812414   9.13897189  8.89516917  7.6173951 ]] [[[10  8  2  0  0]
  [12 13  2  0  0]
  [ 8  8  2  0  8]
  [11  9  3  0 10]
  [12 13  2  0  0]]

 [[10  8  2  0  0]
  [10  8  2  0  0]
  [ 8  8  2  0  8]
  [11  9  3  0 10]
  [16 14  4  0  6]]

 [[ 6  7  2  1 15]
  [16 15  3  0  0]
  [ 8  8  2  0  8]
  [ 7  6  2  0 10]
  [ 9 11  2  0  0]]

 ...

 [[ 9 11  2  0  0]
  [16 15  3  0  0]
  [ 8 10  2  0  0]
  [ 7  6  2  0 10]
  [ 7  6  2  0 10]]

 [[ 9  8  2  1 15]
  [11 10  3  0  4]
  [ 8 10  2  0  0]
  [11  9  3  0 10]
  [11  9  3  0 10]]

 [[16 15  3  0  0]
  [12 12  2  1 12]
  [ 8 10  2  0  0]
  [11  9  3  0 10]
  [10  8  2  0  0]]] [array([[ 9, 13,  6, 10, 13]

In [47]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(lr, xtrain, ytrain, scoring='r2', cv=5)
scores   

array([0.78851745, 0.81347201, 0.81604887, 0.89868484, 0.84237804])